title: "ECB+GPT Experiments"
description: ""

vars:
  gpu: 0
  ecb-dir: corpus/ecb
  ecb-mention-map: corpus/ecb/mention_map.pkl
  doc-sent-map: corpus/ecb/doc_sent_map.pkl
  model-save-path: outputs/models/biencoder/

directories:
  - "assets"
  - "corpus"
  - "scripts"
  - "outputs"

assets:
  - dest: "assets/ecb"
    help: "The Event Coref Bank Plus Corpus"
    git:
      repo: "https://github.com/cltl/ecbPlus"
      branch: "master"
      path: "ECB+_LREC2014"

commands:
  - name: "ecb-setup"
    help: "Preprocess and Create mention_map from ECB+ corpus"
    script:
      - python -m scripts.parse_ecb parse-annotations assets/ecb ${vars.ecb-dir} en_core_web_lg
    deps:
      - assets/ecb
    outputs:
      - ${vars.ecb-mention-map}
      - ${vars.doc-sent-map}

  - name: "train_biencoder"
    help: "Train the biencoder model on ECB+ corpus"
    script:
      - >- 
        python -m scripts.nn_method.train
        ${vars.ecb-mention-map}
        --model-name /home/rehan/workspace/models/ce_models/ecb_small/bert
        --text-key neighbors_2
        --learning-rate 0.00001
        --batch-size 4
        --epochs 20
        --save-path ${vars.model-save-path} 

  - name: "knn-bert"
    help: "Run the coreference pipeline with KNN filtering and BERT CrossEncoder"
    script:
      - >- 
        python -m scripts.bert_pipeline run-knn-bert-pipeline 
        corpus/ecb/ dev  /home/rehan/workspace/models/ce_models/ecb_small/bert
        /home/rehan/workspace/models/ce_models/ecb_small/ 
        --knn-file ./outputs/knn/dev_map_100_neigh_3.pkl 
        --top-k 10 
        --ce-score-file ./outputs/ce_neigh_3.pkl
        --ce-threshold 0.5
        --ce-text-key neighbors_3

  - name: "lh-bert"
    help: "Run the coref pipeline with Lemma Heuristic and BERT CrossEncoder"
    script:
      - >-
        python -m scripts.bert_pipeline run-lh-bert-pipeline 
        corpus/ecb/ dev  /home/rehan/workspace/models/ce_models/ecb_small/ 
        --ce-score-file ./outputs/ce_lh_dev.pkl 
        --ce-threshold 0.5

