title: "ECB+GPT Experiments"
description: ""

vars:
  gpu: 0
  ecb-dir: corpus/ecb
  ecb-mention-map: corpus/ecb/mention_map.pkl
  doc-sent-map: corpus/ecb/doc_sent_map.pkl

directories:
  - "assets"
  - "corpus"
  - "scripts"
  - "outputs"

assets:
  - dest: "assets/ecb"
    help: "The Event Coref Bank Plus Corpus"
    git:
      repo: "https://github.com/cltl/ecbPlus"
      branch: "master"
      path: "ECB+_LREC2014"

commands:
  - name: "ecb-setup"
    help: "Preprocess and Create mention_map from ECB+ corpus"
    script:
      - python -m scripts.parse_ecb parse-annotations assets/ecb ${vars.ecb-dir} en_core_web_lg
    deps:
      - assets/ecb
    outputs:
      - ${vars.ecb-mention-map}
      - ${vars.doc-sent-map}

  - name: "knn-bert"
    help: "Run the coreference pipeline with KNN filtering and BERT CrossEncoder"
    script:
      - python -m scripts.bert_pipeline corpus/ecb/ dev  /home/rehan/workspace/models/roberta_ecb/checkpoint-34000/  /home/rehan/workspace/models/ce_models/ecb_small/ --knn-file ./outputs/knn/dev_map_100.pkl --top-k 10 --ce-score-file ./outputs/ce.pkl