title: "ECB+GPT Experiments"
description: ""

vars:
  gpu: 0
  ecb-dir: corpus/ecb
  ecb-mention-map: corpus/ecb/mention_map.pkl
  doc-sent-map: corpus/ecb/doc_sent_map.pkl
  augment-context-path: corpus/ecb/mention_map_with_context.pkl
  augment-candidates-path: corpus/ecb/mention_map_with_candidates.pkl
  label-group-path: corpus/ecb/label_group.pkl
  model-save-path: outputs/models/biencoder/

directories:
  - "assets"
  - "corpus"
  - "scripts"
  - "outputs"

assets:
  - dest: "assets/ecb"
    help: "The Event Coref Bank Plus Corpus"
    git:
      repo: "https://github.com/cltl/ecbPlus"
      branch: "master"
      path: "ECB+_LREC2014"

commands:
  - name: "ecb-setup"
    help: "Preprocess and Create mention_map from ECB+ corpus"
    script:
      - python -m scripts.parse_ecb parse-annotations assets/ecb ${vars.ecb-dir} en_core_web_lg
    deps:
      - assets/ecb
    outputs:
      - ${vars.ecb-mention-map}
      - ${vars.doc-sent-map}

  - name: "augment-context"
    help: "Augments the mention map with context from the document-sentence map."
    script:
      - python -m scripts.augment_ecb augment-context ${vars.ecb-mention-map} ${vars.doc-sent-map} --save-path ${vars.augment-context-path}

  - name: "augment-candidates"
    help: "Adds candidates to the mention map and groups mentions by label."
    script:
      - python -m scripts.augment_ecb augment-candidates ${vars.ecb-mention-map} --map-save-path ${vars.augment-candidates-path} --label-group-save-path ${vars.label-group-path}

  - name: "train_biencoder"
    help: "Train the biencoder model on ECB+ corpus"
    script:
      - >- 
        python -m scripts.nn_method.train
        ${vars.ecb-mention-map}
        --model-name /home/rehan/workspace/models/ce_models/ecb_small/bert
        --text-key neighbors_2
        --learning-rate 0.00001
        --batch-size 4
        --epochs 20
        --save-path ${vars.model-save-path} 

  - name: "save-knn-pairs-bi"
    help: "Save the mention pairs generated by knn"
    script:
      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl train 
        ./outputs/models/biencoder/checkpoint-18/ 
        ./outputs/knn/train_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/train.pairs
        --ce-text-key neighbors_2 
        --top-k 5 --force

      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl dev 
        ./outputs/models/biencoder/checkpoint-18/ 
        ./outputs/knn/dev_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/dev.pairs
        --ce-text-key neighbors_2 
        --top-k 5

      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl debug_split
        ./outputs/models/biencoder/checkpoint-18/
        ./outputs/knn/debug_split_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/debug_split.pairs 
        --ce-text-key neighbors_2 
        --top-k 5

  - name: "save-lh-pairs"
    help: "Save the mention pairs generated using LH"
    script:
      - >-
        python -m scripts.heuristic ./corpus/ecb/
        train lh 0.1 ./outputs/mention_pairs/lh/train.pairs
      - >-
        python -m scripts.heuristic ./corpus/ecb
        dev lh 0.1 ./outputs/mention_pairs/lh/dev.pairs
      - >- 
        python -m scripts.heuristic ./corpus/ecb/
        debug_split lh 0.1 ./outputs/mention_pairs/lh/debug_split.pairs

  - name: "save-lh-knn-pairs"
    help: "Merge the pairs from LH and KNN"
    script:
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/train.pairs
        ./outputs/mention_pairs/knn/train.pairs
        ./outputs/mention_pairs/lh_knn/train.pairs
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/dev.pairs
        ./outputs/mention_pairs/knn/dev.pairs
        ./outputs/mention_pairs/lh_knn/dev.pairs
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/debug_split.pairs
        ./outputs/mention_pairs/knn/debug_split.pairs
        ./outputs/mention_pairs/lh_knn/debug_split.pairs

  - name: "knn-bert"
    help: "Run the coreference pipeline with KNN filtering and BERT CrossEncoder"
    script:
      - >- 
        python -m scripts.bert_pipeline run-knn-bert-pipeline 
        corpus/ecb/ dev  /home/rehan/workspace/models/ce_models/ecb_small/bert
        /home/rehan/workspace/models/ce_models/ecb_small/ 
        --knn-file ./outputs/knn/dev_map_100_neigh_3.pkl 
        --top-k 10 
        --ce-score-file ./outputs/ce_neigh_3.pkl
        --ce-threshold 0.99
        --ce-text-key neighbors_3

  - name: "lh-bert"
    help: "Run the coref pipeline with Lemma Heuristic and BERT CrossEncoder"
    script:
      - >-
        python -m scripts.bert_pipeline
        corpus/ecb/ dev  /home/rehan/workspace/models/ce_models/ecb_small/ 
        --ce-score-file ./outputs/ce_lh_dev.pkl 
        --ce-threshold 0.0

  - name: "knn-lh-bert"
    help: "Run the coreference pipeline with KNN filtering and BERT CrossEncoder"
    script:
      - >-
        python -m scripts.bert_pipeline run-knn-lh-bert-pipeline 
        corpus/ecb/ dev  /home/rehan/workspace/models/ce_models/ecb_small/bert
        /home/rehan/workspace/models/ce_models/ecb_small/ 
        --knn-file ./outputs/knn/dev_map_100_neigh_2.pkl 
        --top-k 3 
        --ce-score-file ./outputs/ce_lh_tp_neigh_2.pkl
        --ce-threshold 0.0
        --ce-text-key neighbors_2
        --ce-force

  - name: "llm"
    help: "Run coreference pipeline with LLM reasoning"
    script:
      - >-
        python -m scripts.llm_pipeline run-llm-pipeline
        corpus/ecb/ debug_split /Users/ERWAN2/projects/llms_coref/project/corpus/ecb/knn_neighbors_2_top3.pkl
        --gpt-version gpt-3.5-turbo
        --save-folder outputs/llms/debug/knn
        --experiment-name twoshot

  - name: "save-knn-pairs-ce"
    help: "Save the mention pairs generated by knn"
    script:
      - >-
        python -m scripts.knn save-knn-mention-pairs-ce
        ./corpus/ecb/mention_map.pkl ./outputs/mention_pairs/knn/train.pairs
        /media/rehan/big_disk/models/ce_lh/
        ./outputs/knn/train_neighbors_2.pkl 
        ./outputs/mention_pairs/knn_ce/train.pairs
        --ce-text-key neighbors_2 
        --top-k 5
        --force

      - >-
        python -m scripts.knn save-knn-mention-pairs-ce
        ./corpus/ecb/mention_map.pkl ./outputs/mention_pairs/knn/dev.pairs 
        /media/rehan/big_disk/models/ce_lh/
        ./outputs/knn/dev_neighbors_2.pkl 
        ./outputs/mention_pairs/knn_ce/dev.pairs
        --ce-text-key neighbors_2 
        --top-k 5
        --force

      - >-
        python -m scripts.knn save-knn-mention-pairs-ce
        ./corpus/ecb/mention_map.pkl ./outputs/mention_pairs/knn/debug_split.pairs
        /media/rehan/big_disk/models/ce_lh/
        ./outputs/knn/debug_split_neighbors_2.pkl 
        ./outputs/mention_pairs/knn_ce/debug_split.pairs 
        --ce-text-key neighbors_2 
        --top-k 5
        --force