title: "ECB+GPT Experiments"
description: ""

vars:
  gpu: 0
  ecb-dir: corpus/ecb
  ecb-mention-map: corpus/ecb/mention_map.pkl
  doc-sent-map: corpus/ecb/doc_sent_map.pkl
  augment-context-path: corpus/ecb/mention_map_with_context.pkl
  augment-candidates-path: corpus/ecb/mention_map_with_candidates.pkl
  label-group-path: corpus/ecb/label_group.pkl
  model-save-path: outputs/models/biencoder/

directories:
  - "assets"
  - "corpus"
  - "scripts"
  - "outputs"

assets:
  - dest: "assets/ecb"
    help: "The Event Coref Bank Plus Corpus"
    git:
      repo: "https://github.com/cltl/ecbPlus"
      branch: "master"
      path: "ECB+_LREC2014"

commands:
  - name: "ecb-setup"
    help: "Preprocess and Create mention_map from ECB+ corpus"
    script:
      - python -m scripts.parse_ecb parse-annotations assets/ecb ${vars.ecb-dir} en_core_web_lg
    deps:
      - assets/ecb
    outputs:
      - ${vars.ecb-mention-map}
      - ${vars.doc-sent-map}

  - name: "train-biencoder-triplet"
    help: "Train the biencoder model on ECB+ corpus"
    script:
      - >- 
        python -m scripts.bert.train train-biencoder
        ./corpus/ecb/mention_map.pkl
        --model-name /media/rehan/big_disk/models/bi_final/checkpoint-2/
        --text-key marked_sentence
        --learning-rate 0.00001
        --batch-size 4
        --epochs 20
        --save-path /media/rehan/big_disk/models/bi_final/ 

  - name: "save-knn-pairs-bi"
    help: "Save the mention pairs generated by knn"
    script:
      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl train 
        /media/rehan/big_disk/models/bi_final/checkpoint-18/
        ./outputs/knn_distil_n_3/train_neighbors_3.pkl 
        ./outputs/mention_pairs/knn/train.pairs
        --ce-text-key neighbors_3 
        --top-k 5

      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl dev 
        /media/rehan/big_disk/models/bi_final/checkpoint-18/
        ./outputs/knn_distil_n_3/dev_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/dev.pairs
        --ce-text-key neighbors_3 
        --top-k 5

      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl debug_split
         /media/rehan/big_disk/models/bi_final/checkpoint-18/
        ./outputs/knn_distil_n_3/debug_split_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/debug_split.pairs 
        --ce-text-key neighbors_3 
        --top-k 3 

      - >-
        python -m scripts.knn save-knn-mention-pairs
        ./corpus/ecb/mention_map.pkl test
         ./outputs/models/biencoder/checkpoint-18/
        ./outputs/knn_distil_n_3/test_neighbors_2.pkl 
        ./outputs/mention_pairs/knn/test.pairs 
        --ce-text-key neighbors_3 
        --top-k 5 

  - name: "save-lh-pairs"
    help: "Save the mention pairs generated using LH"
    script:

      - >- 
        python -m scripts.heuristic ./corpus/ecb_sum_gpt4/
        train lh 0.05 ./outputs/mention_pairs/ecb_sum_gpt4/lh_fn/train.pairs --add-fn
      - >-
        python -m scripts.heuristic ./corpus/ecb_sum_gpt4/
        dev lh 0.05 ./outputs/mention_pairs/ecb_sum_gpt4/lh_fn/dev.pairs --add-fn
      - >-
        python -m scripts.heuristic ./corpus/ecb_sum_gpt4/
        debug_split lh 0.05 ./outputs/mention_pairs/ecb_sum_gpt4/lh_fn/debug_split.pairs --add-fn

  - name: "save-lh-knn-pairs"
    help: "Merge the pairs from LH and KNN"
    script:
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/train.pairs
        ./outputs/mention_pairs/knn/train.pairs
        ./outputs/mention_pairs/lh_knn/train.pairs
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/dev.pairs
        ./outputs/mention_pairs/knn/dev.pairs
        ./outputs/mention_pairs/lh_knn/dev.pairs
      - >-
        python -m scripts.knn merge-mention-pairs
        ./outputs/mention_pairs/lh/debug_split.pairs
        ./outputs/mention_pairs/knn/debug_split.pairs
        ./outputs/mention_pairs/lh_knn/debug_split.pairs

  - name: "save-bs-pairs"
    help: "Merge the pairs from LH and KNN"
    script:
      - >-
        python -m scripts.knn save-knn-pairs-bert-score 
        ./corpus/ecb/mention_map.pkl dev dev 
        ./outputs/mention_pairs/bs/dev.pairs 
        --text-key marked_sentence 
        --top-k 5
        --same-topic
      - >-
        python -m scripts.knn save-knn-pairs-bert-score 
        ./corpus/ecb/mention_map.pkl debug_split debug_split 
        ./outputs/mention_pairs/bs/debug_split.pairs 
        --text-key marked_sentence 
        --top-k 3
        --same-topic

      - >-
        python -m scripts.knn save-knn-pairs-bert-score 
        ./corpus/ecb/mention_map.pkl test test 
        ./outputs/mention_pairs/bs/test.pairs 
        --text-key marked_sentence 
        --top-k 5
        --same-topic

  - name: "llm"
    help: "Run coreference pipeline with LLM reasoning"
    script:
      - >-
        python -m scripts.llm_pipeline run-llm-pipeline
        corpus/ecb_sum/ debug_split ./outputs/mention_pairs/ecb_sum/lh/debug_split.pairs
        ./outputs/llms/debug/ecb_sum_prec_AMR.lh.pkl
        --gpt-raw-cache-dir ./outputs/cache/ecb_sum_prec/
        --gpt-version gpt-3.5-turbo
        --save-folder outputs/llms/debug_sum_prec/lh
        --experiment-name amr
        --text-key marked_sentence

  - name: "heuristics"
    help: "Calculate the heurisitcs baseline with CE"
    script:
      - echo "----------- LH - Dev ---------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
        ./corpus/ecb/mention_map.pkl
        dev ./outputs/mention_pairs/lh/dev.pairs

      - echo "-------- - LH - DEBUG-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
        ./corpus/ecb/mention_map.pkl
        debug_split ./outputs/mention_pairs/lh/debug_split.pairs

      - echo "-------- - LH - TEST-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
        ./corpus/ecb/mention_map.pkl
        test ./outputs/mention_pairs/lh/test.pairs

      - echo "-------- - KNN - DEV-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          dev ./outputs/mention_pairs/knn/dev.pairs

      - echo "-------- - KNN - DEBUG-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          debug_split ./outputs/mention_pairs/knn/debug_split.pairs

      - echo "-------- - KNN - TEST-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          test ./outputs/mention_pairs/knn/test.pairs

      - echo "-------- - BS - DEV-------------"
      -  >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          dev ./outputs/mention_pairs/bs/dev.pairs
      - echo "-------- - BS - DEBUG-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          debug_split ./outputs/mention_pairs/bs/debug_split.pairs

      - echo "-------- - BS - TEST-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          test ./outputs/mention_pairs/bs/test.pairs

      - echo "-------- - LH+KNN - DEV-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          dev ./outputs/mention_pairs/lh_knn/dev.pairs
      - echo "-------- - LH+KNN - DEBUG-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          debug_split ./outputs/mention_pairs/lh_knn/debug_split.pairs

      - echo "-------- - LH+KNN - TEST-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          test ./outputs/mention_pairs/lh_knn/test.pairs

      - echo "-------- - LH+KNN+BS - DEV-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          dev ./outputs/mention_pairs/lh_knn_bs/dev.pairs
      - echo "-------- - LH+KNN+BS - DEBUG-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          debug_split ./outputs/mention_pairs/lh_knn_bs/debug_split.pairs

      - echo "-------- - LH+KNN+BS - TEST-------------"
      - >-
        python -m scripts.heuristics_pipeline --oracle
          ./corpus/ecb/mention_map.pkl
          test ./outputs/mention_pairs/lh_knn_bs/test.pairs

  - name: "merge-lh-knn-bs"
    help: "Merge the mention pairs generated by LH, KNN and BERTScore"
    script:
      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh/debug_split.pairs 
          ./outputs/mention_pairs/knn/debug_split.pairs 
          ./outputs/mention_pairs/lh_knn/debug_split.pairs

      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh/test.pairs 
          ./outputs/mention_pairs/knn/test.pairs 
          ./outputs/mention_pairs/lh_knn/test.pairs

      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh/dev.pairs 
          ./outputs/mention_pairs/knn/dev.pairs 
          ./outputs/mention_pairs/lh_knn/dev.pairs

      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh_knn/debug_split.pairs 
          ./outputs/mention_pairs/bs/debug_split.pairs 
          ./outputs/mention_pairs/lh_knn_bs/debug_split.pairs

      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh_knn/test.pairs 
          ./outputs/mention_pairs/bs/test.pairs 
          ./outputs/mention_pairs/lh_knn_bs/test.pairs

      - >-
        python -m scripts.knn merge-mention-pairs 
          ./outputs/mention_pairs/lh_knn/dev.pairs 
          ./outputs/mention_pairs/bs/dev.pairs 
          ./outputs/mention_pairs/lh_knn_bs/dev.pairs

  - name: "train-crossencoder"
    help: "Train the crossencoder by providing train and dev mention pairs"
    script:
      - >-
        python -m scripts.bert.train train-cross-encoder 
        ./corpus/ecb_sum_gpt4/ 
        ./outputs/mention_pairs/ecb_sum_gpt4/lh_fn/train.pairs 
        ./outputs/mention_pairs/ecb_sum_gpt4/lh_fn/dev.pairs 
        /media/rehan/big_disk/models/ce/lh_fn_summ_roberta-base
        --model-name roberta-base 
        --text-key marked_sentence
        --batch-size 64 
        --epochs 50
        --max-sentence-len 256

  - name: "lh-meta-test"
    help: "Run the heuristic results on ecb meta"
    script:
     - echo "---------------TEST------------------"
     - >-
       python -m scripts.heuristics_pipeline 
          ./corpus/ecb_meta/mention_map.pkl
          test ./outputs/mention_pairs/ecb_meta/lh/test.pairs
     - echo "---------------DEBUG------------------"
     - >-
       python -m scripts.heuristics_pipeline 
                 ./corpus/ecb_meta/mention_map.pkl
                 debug_split ./outputs/mention_pairs/ecb_meta/lh/debug_split.pairs

  - name: "bert-lh-knn-bs"
    help: "Run the BERT pipeline on trained model"
    script:
      - >-
        python -m scripts.bert_pipeline ./corpus/ecb/ 
        debug_split ./outputs/mention_pairs/lh_knn_bs/debug_split.pairs
        /media/rehan/big_disk/models/ce/lh_fn_knn_bs_rob-large/scorer/chk_6/ 
        --text-key neighbors_3 
        --max-sentence-len 
        512 --ce-score-file 
        ./outputs/final_scores_ce/debug_lh_knn_bs.pkl